In [3]:
#!/usr/bin/env python3
## import libraries
import numpy as np
import pandas as pd
from keras.models import load_model
from keras.preprocessing import sequence
import matplotlib.pyplot as plt
import tensorflow as tf

Using TensorFlow backend.
/home/lab606a/.virtualenvs/keras/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/lab606a/.virtualenvs/keras/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/lab606a/.virtualenvs/keras/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/lab606a/.virtualenvs

In [4]:
# set GPU memory
gpu_options = tf.GPUOptions(allow_growth=True)
sess = tf.Session(config=tf.ConfigProto(gpu_options=gpu_options))

In [5]:
model = load_model('./saved model/500_data/prediction_not_fixed_top5')

In [6]:
dataset = pd.read_csv("./datasets/split by random for distributed/prediction/top5_test.csv", header=None)
dataset = dataset.fillna(0)
dataset

0        1        2         3        4        5         6    \
0     98.2815  302.499  43.4676   96.9341  292.527  45.9779   95.5062   
1     49.2123  286.334  42.7695   48.9613  276.363  44.8216   48.7738   
2    112.8700  299.723  43.2408  111.9300  288.898  44.8629  110.7920   
3    118.7660  289.277  42.6587  117.3220  277.631  44.9817  115.8250   
4     77.3434  323.038  43.3315   77.5085  313.501  45.7540   77.6320   
..        ...      ...      ...       ...      ...      ...       ...   
245   68.9601  284.768  40.7917   69.0397  271.469  42.6744   68.5909   
246   68.9769  301.014  44.6484   69.0480  290.905  46.6590   68.8589   
247   94.6610  316.460  44.9202   93.8949  305.949  47.1931   93.1668   
248   36.8026  303.074  43.7032   36.2891  292.288  45.0557   36.1343   
249   75.8097  305.149  44.3227   75.7365  296.465  45.5896   75.8979   

         7        8         9    ...      128  129  130  131  132  133  134  \
0    280.345  48.7612   94.1041  ...   0.0000  0.0  0.0  0.0  0.0  0.0  0.0   
1    265.579  46.4913   48.9726  ...   0.0000  0.0  0.0  0.0  0.0  0.0  0.0   
2    278.619  46.1567  109.9550  ...   0.0000  0.0  0.0  0.0  0.0  0.0  0.0   
3    267.763  47.0061  114.5390  ...   0.0000  0.0  0.0  0.0  0.0  0.0  0.0   
4    301.557  47.9476   77.7495  ...   0.0000  0.0  0.0  0.0  0.0  0.0  0.0   
..       ...      ...       ...  ...      ...  ...  ...  ...  ...  ...  ...   
245  263.878  43.1709   68.6592  ...   0.0000  0.0  0.0  0.0  0.0  0.0  0.0   
246  281.277  48.0806   68.9315  ...  33.7456  0.0  0.0  0.0  0.0  0.0  0.0   
247  295.935  49.1059   92.4186  ...  32.4635  0.0  0.0  0.0  0.0  0.0  0.0   
248  280.696  46.0372   35.6420  ...   0.0000  0.0  0.0  0.0  0.0  0.0  0.0   
249  285.378  47.2049   75.8020  ...   0.0000  0.0  0.0  0.0  0.0  0.0  0.0   

     135  136  137  
0      0    0    0  
1      0    0    0  
2      0    0    0  
3      0    0    0  
4      0    0    0  
..   ...  ...  ...  
245    0    0    0  
246    0    0    0  
247    0    0    0  
248    0    0    0  
249    0    0    0  

[250 rows x 138 columns]

In [7]:
np.set_printoptions(suppress=True)

In [8]:
dataset = np.array(dataset)

In [33]:
tmp = dataset[1,:]
tmp

array([ 49.2123  , 286.334   ,  42.7695  ,  48.9613  , 276.363   ,
        44.8216  ,  48.7738  , 265.579   ,  46.4913  ,  48.9726  ,
       252.83    ,  48.6959  ,  48.1842  , 245.381   ,  49.1585  ,
        47.8428  , 234.81    ,  49.906   ,  47.7888  , 223.73    ,
        50.3371  ,  47.3987  , 215.157   ,  50.4297  ,  47.3336  ,
       205.036   ,  49.9887  ,  47.3295  , 194.418   ,  49.5329  ,
        46.7958  , 185.961   ,  48.4039  ,  46.5907  , 176.145   ,
        47.2449  ,  46.3851  , 166.747   ,  45.7623  ,  46.2254  ,
       156.953   ,  43.7619  ,  46.1472  , 147.544   ,  43.7371  ,
        45.6209  , 137.688   ,  39.3842  ,  45.2281  , 129.651   ,
        36.3132  ,  45.6233  , 118.173   ,  36.6606  ,  44.4656  ,
       112.324   ,  29.7709  ,  44.2584  , 103.229   ,  26.3395  ,
        43.7702  ,  95.512   ,  22.0732  ,  43.5477  ,  86.9612  ,
        17.7139  ,  43.248   ,  78.1052  ,  13.6546  ,  44.0215  ,
        68.2398  ,  13.4545  ,  42.9508  ,  60.8393  ,   4.053

In [34]:
def calculate_vis_hitting_point(arr):
    __hitting_point = -45
    if (-50 <= float(np.min(arr)) <= -45):
        index = np.argmin(arr)
        row = int((index-0)/3)
        w1 = (arr[row,1]-__hitting_point) / (arr[row,1]-arr[row-1,1])
        __vis_hitting_point = (1-w1)*arr[row,:] + w1*arr[row-1,:]
    elif (-45 < float(np.min(arr)) < -40):
        index = np.argmin(arr)
        row = int((index-0)/3)
        w1 = (arr[row,1]-__hitting_point) / (arr[row-1,1]-arr[row,1])
        __vis_hitting_point = arr[row,:] - w1*(arr[row-1,:]-arr[row,:])
    print("vis hitting point = ", __vis_hitting_point)

In [35]:
calculate_vis_hitting_point(tmp.reshape(int(tmp.shape[0]/3),3))

vis hitting point =  [ 39.18659043 -45.          28.95489967]


In [73]:
def set_data(arr):
    if np.min(arr) <= -45:
        t = arr[np.argmin(arr)-4:np.argmin(arr)-1,]
        print(t)
    else:
        t = arr[np.argmin(arr)-4:np.argmin(arr)+2,]
        print(t)
    tt = sequence.pad_sequences(t.reshape(1,2*3), maxlen=27, padding='post', dtype='float32')
    print("ttt = \n ", tt)
    return tt

In [74]:
tt = set_data(tmp)

[ 41.1058 -34.8233  30.4943  39.6495 -42.5454  29.3262]
ttt = 
  [[ 41.1058 -34.8233  30.4943  39.6495 -42.5454  29.3262   0.       0.
    0.       0.       0.       0.       0.       0.       0.       0.
    0.       0.       0.       0.       0.       0.       0.       0.
    0.       0.       0.    ]]


In [72]:
pred = model.predict(tt.reshape(1,9,3))
pred

array([[[-0.6490135 , -1.2935333 ,  0.03667831],
        [-0.5799141 , -1.20084   , -0.00951576],
        [-0.54400253, -1.134037  , -0.02802467],
        [-0.5728569 , -1.1737862 , -0.01372147],
        [-0.5836258 , -1.1870155 , -0.01648712],
        [-0.58145905, -1.183281  , -0.01719475],
        [-0.57841873, -1.1781769 , -0.01745796],
        [-0.5755882 , -1.1734276 , -0.01748085],
        [-0.5731163 , -1.1693306 , -0.01734924]]], dtype=float32)